modLoader="javafml"
loaderVersion="[35,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/Save-My-Stronghold/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/save-my-stronghold"
logoFile="SMSLogo.png"

[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="${modName}"
	credits="${modCredits}"
	authors="${modAuthor}"
	description="${modDescription}"

[[dependencies.savemystronghold]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="SERVER"