modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/yungnickyoung/Save-My-Stronghold/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/save-my-stronghold"
logoFile="SMSLogo.png"

[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="${modName}"
	updateJSONURL="https://raw.githubusercontent.com/yungnickyoung/Save-My-Stronghold/1.14.4/versions.json"
	credits="${modCredits}"
	authors="${modAuthor}"
	description="${modDescription}"

[[dependencies.savemystronghold]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.savemystronghold]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"