modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/yungnickyoung/Save-My-Stronghold/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/save-my-stronghold"
logoFile="SMSLogo.png"

[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="${modName}"
	credits="${modCredits}"
	authors="${modAuthor}"
	description="${modDescription}"

[[dependencies.savemystronghold]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.savemystronghold]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"